name: CI to Docker Hub

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker image tag'
        required: true
        default: latest
      branch:
        description: "Branch name"
        required: true
        default: main
      dockerhub_user:
        description: 'Docker hub user'
        required: true
        default: YOUR_DOCKERHUB_USERNAME 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2  
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          ref: ${{ github.event.inputs.branch }}
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.event.inputs.dockerhub_user }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./demo.df
          push: true
          tags: surepatientdev/demo:${{ github.event.inputs.docker_tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
